# coding: utf-8
from __future__ import unicode_literals

# Helper function to simply tell whether or not the given word is a number.
def is_num(s):
    try:
        float(s)
        return True
    except ValueError:
        return False

class FE_Dict():
    """docstring for FE_Dict"""
    def __init__(self):
        self.dict = {
            "a": ["to"],
            "à": ["to", "in", "at", "with", "by", "upon"],
            "ai": ["have"],
            "au": ["the"],
            "aux" : ['the'],
            "ce": ["this", "it", "that"],
            "ces": ["these", "this", "that"],
            "de": ["of", "to", "from", "by", "with", "than", "at", "out of", "off"],
            "des": ["of"],
            "elle" : ['it', 'she', 'her', 'herself'],
            "en": ["in", "into", "to", "at", "of"],
            "est": ["is", "east", "eastern"],
            "et": ["and"],
            "il": ["the"],
            "ils": ["they", "those"],
            "je": ["I"],
            "le": ["the", "it", "him"],
            "les": ["the", "them"],
            "la": ["the", "a", "there", "it", "her"],
            "me": ["me", "myself"],
            "où": ["where", "that", "wherein", "whither", "whereabouts"],
            "que": ["that", "than"],
            "se": ["themselves", "himself", "herself"],
            "sa": ["its", "his", "her"],
            "sans" : ['without', 'wanting'],
            "son": ["its", "his", "her", "sound"],
            "un": ["a", "an", "one"],
            "une": ["a", "an", "one"],
            "technologies": ["technologies", "technology", "tech"],
            "hautes": ["high", "tall"],
            "explosion": ["explosion", "burst", "blast", "outburst", "detonation", "outbreak"],
            "avant": ["before", "prior", "until", "front"],
            "existait": ["exist", "be"],
            "transhumanisme": ["transhumanism"],
            "immortalité": ["immortality"],
            "accédera": ["will access", "get to"],
            "artificielle": ["artificial"],
            "intelligence": ["intelligence", "intellect", "mind", "understanding", "brains", "cleverness"],
            "grâce": ["grace", "blessing", "pardon"],
            "ordinateur": ["computer"],
            "avec": ["with", "along with", "together with", "to"],
            "plus": ["more", "most", "further", "plus"],
            "fera": ["will", "do", "make", "take"],
            "ne": ["not"],
            "corps": ["body", "corpse"],
            "tranche" : ['slice', 'piece', 'tranche', 'wafer', 'installment', 'instalment', 'block', 'round', 'slab', 'sliver', 'steak', 'slat'],
            "cette" : ['this', 'that'],
            "monstruosité" : ['monstrosity', 'deformity'],
            "contient" : ['contain', 'hold', 'hold in', 'check', 'restrain', 'stem', 'staunch', 'stanch', 'accomodate', 'subdue', 'tame', 'smother', 'repress', 'govern', 'push back', 'dam'],
            "seule" : ['only', 'alone', 'single', 'only one', 'sole', 'mere', 'lonesome', 'lonely', 'unaccompanied', 'bachelor', 'lone', 'very'],
            "calories" : ['calories'],
            "libérera": ["release"],
            "photo": ["photo", "picture"],
            "appareil": ["apparatus", "device", "unit", "appliance", "machine"],
            "helices": ["propellers", "screw"],
            "trois": ["three"],
            "doté": ["with"],
            "physique": ["physique", "physical"],
            "drone": ["drone"],
            "petit": ["small", "little", "short"],
            "concurrence": ["competition", "contest", "contention"],
            "cette": ["this", "that"],
            "favorables": ["favorable", "good", "beneficial"],
            "pourtant": ["yet", "however", "nevertheless", "nonetheless"],
            "sont": ["be", "exist"],
            "droite": ["right"],
            "comme": ["such as", "as", "like"],
            "gauche": ["left"],
            "élus": ["elected"],
            "année": ["year"],
            "chaque": ["each", "every", "either"],
            "france": ["France"],
            "préventives": ["preventative"],
            "fouilles": ["excavation", "dig"],
            "dizaines": ["decades"],
            "repoussait": ["repel", "repulse", "fend off", "drive back"],
            "anglais": ["English", "British"],
            "supporteurs": ["supporters", "fans", "backer"],
            "groupe": ["group", "band", "batch", "unit", "party", "cluster"],
            "wagon": ["car", "wagon"],
            "entrer": ["enter", "come in", "go in", "get in"],
            "voulu": ["desired", "intended", "required"],
            "reproduire": ["reproduce", "replicate", "copy", "repeat"],
            "bien": ["good", "well", "right"],
            "chances": ["chances", "odds"],
            "leurs": ["their"],
            "attaque": ["attack", "offense", "offensive", "drive"],
            "pollution": ["pollution", "contamination", "dirtiness"],
            "obésité": ["obesity"],
            "développé": ["developed"],
            "médecins": ["doctors"],
            "surprise": ["surprise", "astonishment", "shock", "suddenness"],
            "mais": ["but", "although", "yet", "only", "probably"],
            "locale": ["local", "topical", "native"],
            "pègre": ["underworld"],
            "rapproche": ["close", "near"],
            "encourent": ["incur"],
            "interdiction": ["prohibition", "banning", "forbidding", "interdict", "suppression", "outlawry", "lid"],
            "vie": ["life", "living", "lifetime", "career"],
            "football": ["football"],
            "doit": ["must"],
            "lutter": ["fight", "combat", "struggle", "battle", "strive", "cope", "wrestle", "war", "contest", "vie", "strike", "tug", "agonize", "buffet", "heave", "worry"],
            "quotidien": ["daily", "everyday", "newspaper", "quotidian"],
            "contre": ["against", "versus", "anti"],
            "racisme": ["racism", "racialism"],
            "poursuivi": ["pursued"],
            "pour": ["for", "to", "of", "toward", "towards"],
            "assassinats": ["assassinations", "murders"],
            "risque": ["risk", "hazard", "danger", "peril", "riskiness"],
            "peine": ["penalty", "sentence", "trouble", "pain", "sorrow", "grief", "pains", "heartache", "ache", "forfeit", "bitterness", "gruel", "infirmity"],
            "mort": ["dead", "died", "dying", "gone", "extinct", "demise", "exit", "fate", "doom", "dummy", "casualty"],
            "entreprise": ["business", "company", "enterprise", "undertaking", "firm", "venture", "attempt"],
            "augmente": ["increase", "augment", "raise", "rise", "enhance", "grow", "expand", "boost", "extend"],
            "salaire": ["salary", "wage", "pay", "wages", "reward", "earning", "stipent", "screw"],
            "demi": ["half"],
            "million": ["million"],
            "employés": ["employees"],
            "rejoint": ["joined"],
            "bordeaux": ["Bordeaux"],
            "retrouve": ["find", "recover", "retrieve", "meet", "trace"],
            "mère": ["mother", "parent", "mom"],
            "biologique": ["biological", "biologic"],
            "fréquente": ["frequent"],
            "monde": ["world", "people", "earth", "realm", "kingdom"],
            "nuit": ["night", "darkness"],
            "longtemps" : ['for a long time', 'longtime', 'long-standing'],
            "majeure" : ['major', 'middle finger', 'medium finger'],
            "partie" : ['part', 'potion', 'party', 'section', 'game', 'proportion', 'match', 'round', 'stretch', 'slice', 'parcel', 'hand', 'stroke'],
            "communauté" : ['community', 'commune', 'cluster'],
            "scientifique" : ['scientific', 'scientist'],
            "restée" : ['remained'],
            "réaction" : ['reaction', 'response', 'feedback'],
            "face" : ['face', 'front', 'side', 'obverse'],
            "thèses" : ['thesis', 'dissertation', 'theory'],
            "transhumanistes" : ['transhumanists'],
            "jugeait" : ['judge', 'try', 'adjudicate', 'assess', 'decide', 'rule', 'decree', 'sit in judgement', 'arbirate', 'reckon', 'hand down', 'foreordain'],
            "peu" : ['little', 'bit', 'few', 'not very', 'no', 'not much', 'sparsely'],
            "crédibles" : ['credible', 'creditable'],
            "pizza": ["pizza"],
            "également": ["also", "likewise", "equally", "evenly"],
            "surmontée": ["overcome"],
            "bacon": ["bacon"],
            "pepperoni": ["pepperoni"],
            "graisses":["fats", "greases","flabs","fleshes","greasiness"],
            "saturées":["saturated"],
            "trouvent":["find","get","locate","discover","come up with","get it","work","puzzle out","strike on","hit","call"],
            "principalement":["mainly","primarily","principally","chiefly","mostly","predominately"],
            "dans":["in","into","within","on","inside","during","along","aboard"],
            "viandes":["meat"],
            "grasses":["fat","fleshy","fattish"],
            "bloquait":["block","jam","obstruct","close up","lock","clog","trap","tie up","shut out","stop up","peg","snarl"]
        }

    def translate(self, word):
        # Since we don't have translations for every literal number, we'll just
        # first check to see if the given word is a number. If so, give back
        # the original word in a list.
        if is_num(word):
            return [word]

        return self.dict[word]